[package]
name = "rust-learn"
version = "0.1.0"
authors = ["Bora Guven <guvenbe@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crossbeam ="0.8.2"
log = "0.4.20"
env_logger = "0.10.0"
thiserror = "1.0.48"
anyhow = "1.0.75"
