[package]
name = "orphan_rule"
version = "0.1.0"
authors = ["Bora Guven <guvenbe@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crossbeam ="0.8.2"
error-stack = "0.5.0"
log = "0.4.22"
env_logger = "0.11.5"
